### ISSUE TITLE
dte binding changes

### ISSUE THREAD

**Issue by craigbarnes** [zw963/package_payload#2]
Hi! Just to let you know, I [changed] dte recently in a way that affects some of the bindings ([1], [2], [3]) in your [`rc`] file:

```sh
bind C-M-? 'erase-word -s'
bind C-h erase-bol
bind -cs C-h erase-bol
```

The first of these is [bound by default](https://github.com/craigbarnes/dte/blob/4c830bdd9c6f125bd8ab661acf35623d76fb17f6/config/binding/default#L23) (as `M-backspace`), to the same command. Using `bind C-M-? ...` like this will now only match <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>?</kbd>.

The other 2 are [bound by default](https://github.com/craigbarnes/dte/blob/4c830bdd9c6f125bd8ab661acf35623d76fb17f6/config/binding/default#L22) (as `C-backspace`), but to a different command (`erase-word -s` instead of `erase-bol`). This can be addressed by adding the following to your `rc` file:

```
bind -cns C-backspace erase-bol
```

Hope this helps! Unfortunately there was no way to make this improvement to dte without breaking compatibility for these bindings.

[changed]: https://github.com/craigbarnes/dte/commit/706d44666c804053b82b1ad58db06f1797552d3b
[`rc`]: https://github.com/zw963/package_payload/blob/main/packages/dte/.dte/rc
[1]: https://github.com/zw963/package_payload/blob/19393ec7aef3ff1fb6e49b2318b57f8c7805991b/packages/dte/.dte/rc#L65
[2]: https://github.com/zw963/package_payload/blob/19393ec7aef3ff1fb6e49b2318b57f8c7805991b/packages/dte/.dte/rc#L68
[3]: https://github.com/zw963/package_payload/blob/19393ec7aef3ff1fb6e49b2318b57f8c7805991b/packages/dte/.dte/rc#L106

**Comment by zw963** [comment]
> The first of these is [bound by default](https://github.com/craigbarnes/dte/blob/4c830bdd9c6f125bd8ab661acf35623d76fb17f6/config/binding/default#L23) (as M-backspace), to the same command. Using bind C-M-? ... like this will now only match Ctrl+Alt+?.

Thanks, i thought it really clearly now.

> The other 2 are [bound by default](https://github.com/craigbarnes/dte/blob/4c830bdd9c6f125bd8ab661acf35623d76fb17f6/config/binding/default#L22) (as C-backspace), but to a different command (erase-word -s instead of erase-bol). This can be addressed by adding the following to your rc file:

Okay, it reasonable to follow with most of popular editor, `C-backspace` binding to `erase-bol` just one of wierd binding of emacs, i will change my config.

**Comment by zw963** [comment]
Done.

https://github.com/zw963/package_payload/compare/bcd740d..b410706?w=1

thanks very much!

**Comment by zw963** [comment]
Hi, @craigbarnes , just for let you know, there are one more keybinding need to be fix:

C-_ -> C-/

https://github.com/zw963/package_payload/commit/1e4a7c082d1b910e98961093f854be7657d5788e

Thanks

**Comment by craigbarnes** [comment]
> Thanks, i thought it really clearly now.

No problem. I'll add the new special keys to the [man page](https://craigbarnes.gitlab.io/dte/dterc.html#bind) soon.

> ... just for let you know, there are one more keybinding need to be fix:
>
> C-_ -> C-/

Thanks for letting me know! I'm not sure what caused that, to be honest, but I'll look into it. Are you still running WezTerm?

**Comment by zw963** [comment]
>  Are you still running WezTerm?

Yes, I use it exclusively. 

> C-_ -> C-/

I test it on Konsole too, i found konsole still binding `Ctrl + /` into `C-_`, probably this is a wezterm issue?

Anyway, i can add both of them into undo, like following:

```
bind C-_ undo
bind C-M-_ redo
bind C-/ undo
bind C-M-/ redo
```
